INSERT INTO company_addresses VALUES ('AAPL', 'One Apple Park Way', 'Cupertino', 'CA', '95014');
INSERT INTO company_addresses VALUES ('MSFT', 'One Microsoft Way', 'Redmond', 'WA', '98052-6399');
INSERT INTO company_addresses VALUES ('GOOG', '1600 Amphitheatre Parkway', 'Mountain View', 'CA', '94043');
INSERT INTO company_addresses VALUES ('AMZN', '410 Terry Avenue North', 'Seattle', 'WA', '98109-5210');
INSERT INTO company_addresses VALUES ('NVDA', '2788 San Tomas Expressway', 'Santa Clara', 'CA', '95051');
INSERT INTO company_addresses VALUES ('TSLA', '1 Tesla Road', 'Austin', 'TX', '78725');
INSERT INTO company_addresses VALUES ('BRK-B', '3555 Farnam Street', 'Omaha', 'NE', '68131');
INSERT INTO company_addresses VALUES ('META', '1601 Willow Road', 'Menlo Park', 'CA', '94025');
INSERT INTO company_addresses VALUES ('V', 'PO Box 8999', 'San Francisco', 'CA', '94128-8999');
INSERT INTO company_addresses VALUES ('UNH', 'UnitedHealth Group Center', 'Minnetonka', 'MN', '55343');
INSERT INTO company_addresses VALUES ('LLY', 'Lilly Corporate Center', 'Indianapolis', 'IN', '46285');
INSERT INTO company_addresses VALUES ('WMT', '702 South West 8th Street', 'Bentonville', 'AR', '72716');
INSERT INTO company_addresses VALUES ('JPM', '383 Madison Avenue', 'New York', 'NY', '10179');
INSERT INTO company_addresses VALUES ('JNJ', 'One Johnson & Johnson Plaza', 'New Brunswick', 'NJ', '08933');
INSERT INTO company_addresses VALUES ('XOM', '5959 Las Colinas Boulevard', 'Irving', 'TX', '75039-2298');
INSERT INTO company_addresses VALUES ('MA', '2000 Purchase Street', 'Purchase', 'NY', '10577');
INSERT INTO company_addresses VALUES ('PG', 'One Procter & Gamble Plaza', 'Cincinnati', 'OH', '45202');
INSERT INTO company_addresses VALUES ('AVGO', '1320 Ridder Park Drive', 'San Jose', 'CA', '95131-2313');
INSERT INTO company_addresses VALUES ('ORCL', '2300 Oracle Way', 'Austin', 'TX', '78741');
INSERT INTO company_addresses VALUES ('HD', '2455 Paces Ferry Road', 'Atlanta', 'GA', '30339');
INSERT INTO company_addresses VALUES ('MRK', '126 East Lincoln Avenue', 'Rahway', 'NJ', '07065');
INSERT INTO company_addresses VALUES ('CVX', '6001 Bollinger Canyon Road', 'San Ramon', 'CA', '94583-2324');
INSERT INTO company_addresses VALUES ('KO', 'One Coca-Cola Plaza', 'Atlanta', 'GA', '30313');
INSERT INTO company_addresses VALUES ('PEP', '700 Anderson Hill Road', 'Purchase', 'NY', '10577');
INSERT INTO company_addresses VALUES ('ABBV', '1 North Waukegan Road', 'North Chicago', 'IL', '60064-6400');
INSERT INTO company_addresses VALUES ('COST', '999 Lake Drive', 'Issaquah', 'WA', '98027');
INSERT INTO company_addresses VALUES ('BAC', 'Bank of America Corporate Center', 'Charlotte', 'NC', '28255');
INSERT INTO company_addresses VALUES ('ADBE', '345 Park Avenue', 'San Jose', 'CA', '95110-2704');
INSERT INTO company_addresses VALUES ('MCD', '110 North Carpenter Street', 'Chicago', 'IL', '60607');
INSERT INTO company_addresses VALUES ('CSCO', '170 West Tasman Drive', 'San Jose', 'CA', '95134-1706');
INSERT INTO company_addresses VALUES ('CRM', 'Salesforce Tower', 'San Francisco', 'CA', '94105');
INSERT INTO company_addresses VALUES ('PFE', '66 Hudson Boulevard East', 'New York', 'NY', '10001-2192');
INSERT INTO company_addresses VALUES ('TMO', '168 Third Avenue', 'Waltham', 'MA', '02451');
INSERT INTO company_addresses VALUES ('NFLX', '121 Albright Way', 'Los Gatos', 'CA', '95032');
INSERT INTO company_addresses VALUES ('ABT', '100 Abbott Park Road', 'North Chicago', 'IL', '60064-6400');
INSERT INTO company_addresses VALUES ('AMD', '2485 Augustine Drive', 'Santa Clara', 'CA', '95054');
INSERT INTO company_addresses VALUES ('DHR', '2200 Pennsylvania Avenue, North West', 'Washington', 'DC', '20037-1701');
INSERT INTO company_addresses VALUES ('CMCSA', 'One Comcast Center', 'Philadelphia', 'PA', '19103-2838');
INSERT INTO company_addresses VALUES ('TMUS', '12920 SE 38th Street', 'Bellevue', 'WA', '98006-1350');
INSERT INTO company_addresses VALUES ('NKE', 'One Bowerman Drive', 'Beaverton', 'OR', '97005-6453');
INSERT INTO company_addresses VALUES ('DIS', '500 South Buena Vista Street', 'Burbank', 'CA', '91521');
INSERT INTO company_addresses VALUES ('WFC', '420 Montgomery Street', 'San Francisco', 'CA', '94104');
INSERT INTO company_addresses VALUES ('TXN', '12500 TI Boulevard', 'Dallas', 'TX', '75243');
INSERT INTO company_addresses VALUES ('VZ', '1095 Avenue of the Americas', 'New York', 'NY', '10036');
INSERT INTO company_addresses VALUES ('UPS', '55 Glenlake Parkway, N.E.', 'Atlanta', 'GA', '30328');
INSERT INTO company_addresses VALUES ('PM', '677 Washington Boulevard', 'Stamford', 'CT', '06901');
INSERT INTO company_addresses VALUES ('NEE', '700 Universe Boulevard', 'Juno Beach', 'FL', '33408');
INSERT INTO company_addresses VALUES ('RTX', '1000 Wilson Boulevard', 'Arlington', 'VA', '22209');
INSERT INTO company_addresses VALUES ('MS', '1585 Broadway', 'New York', 'NY', '10036');
INSERT INTO company_addresses VALUES ('INTC', '2200 Mission College Boulevard', 'Santa Clara', 'CA', '95054-1549');
INSERT INTO company_addresses VALUES ('HON', '855 South Mint Street', 'Charlotte', 'NC', '28202');
INSERT INTO company_addresses VALUES ('BMY', '430 East 29th Street', 'New York', 'NY', '10016');
INSERT INTO company_addresses VALUES ('LOW', '1000 Lowe’s Boulevard', 'Mooresville', 'NC', '28117');
INSERT INTO company_addresses VALUES ('QCOM', '5775 Morehouse Drive', 'San Diego', 'CA', '92121-1714');
INSERT INTO company_addresses VALUES ('BA', '929 Long Bridge Drive', 'Arlington', 'VA', '22202');
INSERT INTO company_addresses VALUES ('AXP', '200 Vesey Street', 'New York', 'NY', '10285');
INSERT INTO company_addresses VALUES ('SPGI', '55 Water Street', 'New York', 'NY', '10041');
INSERT INTO company_addresses VALUES ('INTU', '2700 Coast Avenue', 'Mountain View', 'CA', '94043');
INSERT INTO company_addresses VALUES ('UNP', '1400 Douglas Street', 'Omaha', 'NE', '68179');
INSERT INTO company_addresses VALUES ('COP', '925 North Eldridge Parkway', 'Houston', 'TX', '77079-2703');
INSERT INTO company_addresses VALUES ('IBM', 'One New Orchard Road', 'Armonk', 'NY', '10504');
INSERT INTO company_addresses VALUES ('AMAT', '3050 Bowers Avenue', 'Santa Clara', 'CA', '95054-3299');
INSERT INTO company_addresses VALUES ('AMGN', 'One Amgen Center Drive', 'Thousand Oaks', 'CA', '91320-1799');
INSERT INTO company_addresses VALUES ('DE', 'One John Deere Place', 'Moline', 'IL', '61265');
INSERT INTO company_addresses VALUES ('GE', '5 Necco Street', 'Boston', 'MA', '02210');
INSERT INTO company_addresses VALUES ('LMT', '6801 Rockledge Drive', 'Bethesda', 'MD', '20817');
INSERT INTO company_addresses VALUES ('ISRG', '1020 Kifer Road', 'Sunnyvale', 'CA', '94086-5304');
INSERT INTO company_addresses VALUES ('PLD', 'Pier 1, Bay 1', 'San Francisco', 'CA', '94111');
INSERT INTO company_addresses VALUES ('T', '208 South Akard Street', 'Dallas', 'TX', '75202');
INSERT INTO company_addresses VALUES ('NOW', '2225 Lawson Lane', 'Santa Clara', 'CA', '95054');
INSERT INTO company_addresses VALUES ('SYK', '2825 Airview Boulevard', 'Kalamazoo', 'MI', '49002');
INSERT INTO company_addresses VALUES ('SBUX', '2401 Utah Avenue South', 'Seattle', 'WA', '98134');
INSERT INTO company_addresses VALUES ('GS', '200 West Street', 'New York', 'NY', '10282');
INSERT INTO company_addresses VALUES ('ELV', '220 Virginia Avenue', 'Indianapolis', 'IN', '46204');
INSERT INTO company_addresses VALUES ('BLK', '50 Hudson Yards', 'New York', 'NY', '10001');
INSERT INTO company_addresses VALUES ('SCHW', '3000 Schwab Way', 'Westlake', 'TX', '76262');
INSERT INTO company_addresses VALUES ('MDLZ', '905 West Fulton Market', 'Chicago', 'IL', '60607');
INSERT INTO company_addresses VALUES ('BKNG', '800 Connecticut Avenue', 'Norwalk', 'CT', '06854');
INSERT INTO company_addresses VALUES ('TJX', '770 Cochituate Road', 'Framingham', 'MA', '01701');
INSERT INTO company_addresses VALUES ('GILD', '333 Lakeside Drive', 'Foster City', 'CA', '94404');
INSERT INTO company_addresses VALUES ('ADI', 'One Analog Way', 'Wilmington', 'MA', '01887');
INSERT INTO company_addresses VALUES ('MMC', '1166 Avenue of the Americas', 'New York', 'NY', '10036-2774');
INSERT INTO company_addresses VALUES ('ADP', 'One ADP Boulevard', 'Roseland', 'NJ', '07068');
INSERT INTO company_addresses VALUES ('AMT', '116 Huntington Avenue', 'Boston', 'MA', '02116-5749');
INSERT INTO company_addresses VALUES ('CVS', 'One CVS Drive', 'Woonsocket', 'RI', '02895');
INSERT INTO company_addresses VALUES ('VRTX', '50 Northern Avenue', 'Boston', 'MA', '02210');
INSERT INTO company_addresses VALUES ('C', '388 Greenwich Street', 'New York', 'NY', '10013');
INSERT INTO company_addresses VALUES ('UBER', '1515 3rd Street', 'San Francisco', 'CA', '94158');
INSERT INTO company_addresses VALUES ('LRCX', '4650 Cushing Parkway', 'Fremont', 'CA', '94538');
INSERT INTO company_addresses VALUES ('CI', '900 Cottage Grove Road', 'Bloomfield', 'CT', '06002');
INSERT INTO company_addresses VALUES ('HCA', 'One Park Plaza', 'Nashville', 'TN', '37203');
INSERT INTO company_addresses VALUES ('MO', '6601 West Broad Street', 'Richmond', 'VA', '23230');
INSERT INTO company_addresses VALUES ('ABNB', '888 Brannan Street', 'San Francisco', 'CA', '94103');
INSERT INTO company_addresses VALUES ('ZTS', '10 Sylvan Way', 'Parsippany', 'NJ', '07054');
INSERT INTO company_addresses VALUES ('PGR', '6300 Wilson Mills Road', 'Mayfield', 'OH', '44143');
INSERT INTO company_addresses VALUES ('PANW', '3000 Tannery Way', 'Santa Clara', 'CA', '95054');
INSERT INTO company_addresses VALUES ('FI', '255 Fiserv Drive', 'Brookfield', 'WI', '53045');
INSERT INTO company_addresses VALUES ('REGN', '777 Old Saw Mill River Road', 'Tarrytown', 'NY', '10591-6707');
INSERT INTO company_addresses VALUES ('SO', '30 Ivan Allen Jr. Boulevard, N.W.', 'Atlanta', 'GA', '30308');